/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
/**
 *
 * @author rb__s
 */

import controllers.ControllerReloj;

import model.Reloj;

import controllers.ControllerValidateInput;

import java.util.ArrayList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;


public class viewRelojFra extends javax.swing.JFrame {

    private ControllerReloj Relojes;
    
    private int id_reloj = 0;
    
    private String hora = "";
    
    private String minuto = "";
    
    private String segundo = "";

    
    
    /**
     * Creates new form viewRelojFra
     */
    public viewRelojFra() {
        initComponents();
        
        this.Relojes = new ControllerReloj();
        
        DefaultTableModel modelT = new DefaultTableModel();
        
         
        /**
         *  CREAMOS EL CALLBACK QUE SE UTILIZARA CUANDO SE PRODUSCA UN EVENTO DEL MOUSE SOBRE LA JTABLE1
         *  EL CALLBACK mouseClicked TRANSFORMARA LOS DATOS DEL RELOJ EN LO DE LA COLUMNA SELECIONADA POR EL EVENO DEL MOUSE CLIEKD
         */
        
         jTable1.addMouseListener(new MouseAdapter(){
            DefaultTableModel modelT = new DefaultTableModel();
            public void mouseClicked(MouseEvent e){
                int i = jTable1.getSelectedRow();
                id_reloj = Integer.parseInt(jTable1.getValueAt(i, 0).toString());
                hora = (jTable1.getValueAt(i, 1).toString());
                minuto = (jTable1.getValueAt(i, 2).toString());
                segundo = (jTable1.getValueAt(i, 3).toString());
                
            }
          });
        
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextHora = new javax.swing.JTextField();
        jTextMinuto = new javax.swing.JTextField();
        jTextSegundos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonGuardarActualizar = new javax.swing.JButton();
        jSegundosMensajeError = new javax.swing.JLabel();
        jHoraErrorMensaje = new javax.swing.JLabel();
        jMinutoErrorMensaje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonCrearRelojBD = new javax.swing.JButton();
        jButtonRelojEliminarBD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonActualizarRelojDB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldHoraBD = new javax.swing.JTextField();
        jTextFieldminutoBD = new javax.swing.JTextField();
        jTextFieldSegundoBD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelShowReloj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_reloj", "Hora", "Minuto", "Segundos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleName("");

        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });

        jTextMinuto.setText("\n");

        jTextSegundos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSegundosActionPerformed(evt);
            }
        });

        jLabel1.setText("hora");

        jLabel2.setText("minuto");

        jLabel3.setText("segundos");

        jLabel4.setText("Agregar Persistencia de Reloj ");

        jButtonCrear.setText("crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonGuardarActualizar.setText("Guardar cambios");
        jButtonGuardarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActualizarActionPerformed(evt);
            }
        });

        jSegundosMensajeError.setForeground(new java.awt.Color(255, 51, 51));

        jHoraErrorMensaje.setForeground(new java.awt.Color(255, 0, 51));

        jMinutoErrorMensaje.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonEliminar)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextHora)
                                        .addComponent(jTextMinuto)
                                        .addComponent(jTextSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonCrear)
                            .addComponent(jSegundosMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMinutoErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jHoraErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jButtonActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jButtonGuardarActualizar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHoraErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextMinuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMinutoErrorMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSegundosMensajeError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCrear)
                            .addComponent(jButtonEliminar)
                            .addComponent(jButtonActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButtonGuardarActualizar.getAccessibleContext().setAccessibleName("guardar actualizacion");
        jButtonGuardarActualizar.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Reloj Persistencia", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id_reloj", "Hora", "Minuto", "Segundos"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Datos");

        jButtonCrearRelojBD.setText("Crear");
        jButtonCrearRelojBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearRelojBDActionPerformed(evt);
            }
        });

        jButtonRelojEliminarBD.setText("Eliminar");
        jButtonRelojEliminarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelojEliminarBDActionPerformed(evt);
            }
        });

        jLabel6.setText("Reloj ");

        jButtonActualizarRelojDB.setText("Actualizar");

        jLabel7.setText("Hora");

        jLabel8.setText("Minuto");

        jLabel9.setText("Segundos");

        jTextFieldminutoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldminutoBDActionPerformed(evt);
            }
        });

        jTextFieldSegundoBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSegundoBDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonCrearRelojBD)
                        .addGap(54, 54, 54)
                        .addComponent(jButtonRelojEliminarBD)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonActualizarRelojDB))
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldSegundoBD, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldminutoBD, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(jTextFieldHoraBD)))))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldHoraBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldminutoBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldSegundoBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearRelojBD)
                    .addComponent(jButtonRelojEliminarBD)
                    .addComponent(jButtonActualizarRelojDB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Base de datos", jPanel2);

        jLabel10.setText("Reloj");

        jLabelShowReloj.setText("Reloj_time");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelShowReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(627, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(102, 102, 102)
                .addComponent(jLabelShowReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Reloj", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSegundosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSegundosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSegundosActionPerformed

    private int ValidateInputDateReloj(String inputdate)
    {
        String input_date = inputdate.replaceAll("\\s+", "");
        
        int val_date = Integer.parseInt(input_date);
        
        return val_date;
        
    }
    
    //CREAR
    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        // TODO add your handling code here:
        // BORRAMOS MENSAJES DE ERRORES 
        clearErrorMensaje();
                
            
       String minutoSinespacios = jTextMinuto.getText();
       String horaSinespacios = jTextHora.getText();
       String segundoSinespacios = jTextSegundos.getText();
       
       /*
       eliminamos los espacion de la entrada de datos
       */
       minutoSinespacios = minutoSinespacios.replaceAll("\\s+", "");
       horaSinespacios = horaSinespacios.replaceAll("\\s+", "");
       segundoSinespacios = segundoSinespacios.replaceAll("\\s+", "");
       
       ///VALIDATE HORA INPUT
       boolean validateinputHora;
       if(ControllerValidateInput.validateInputInteger(horaSinespacios )){
           
           int _hora = Integer.parseInt(horaSinespacios);
           if(ControllerValidateInput.validateHora(_hora)){
               
               validateinputHora = true;
               
           }else{  validateinputHora = false;}
       }else{validateinputHora = false;}
       
       
       ////// validacion de inputminutos
       boolean validateinputMinuto;
       
       if(ControllerValidateInput.validateInputInteger(minutoSinespacios )){
           
           int _minuto = Integer.parseInt(minutoSinespacios);
           if(ControllerValidateInput.validateMinuto(_minuto)){
               
               validateinputMinuto = true;
               
           }else{  validateinputMinuto = false;}
        }else{validateinputMinuto = false;}
       
       
       
       ///VALIDATE SEGUNDOSINPUT
       boolean validateinputSegundos;
         
        if(ControllerValidateInput.validateInputInteger(segundoSinespacios )){
           
           float _segundos = Integer.parseInt(segundoSinespacios);
           if(ControllerValidateInput.validateSegundos(_segundos)){
               
               validateinputSegundos = true;
               
           }else{  validateinputSegundos = false;}
        }else{validateinputSegundos = false;}
       
        
        boolean validate_inputs = mensajeErrorInputs(validateinputHora,validateinputMinuto,validateinputSegundos);
       
       if(validate_inputs){
       
           System.out.print("datos BIEN ingresados \n");
           
             int minuto = Integer.parseInt(minutoSinespacios);
              int hora = Integer.parseInt(horaSinespacios);
               int segundos = Integer.parseInt(segundoSinespacios);
               
                Reloj NuevoReloj = new Reloj(1 ,hora, minuto,segundos);
        
                this.Relojes.crearNuevoReloj(NuevoReloj);
                
                clearErrorMensaje();
                
                clearInputTexts();    
           
       }
       else{
           
            System.out.print("datos mal ingresados\n");
            
    
       }
      

       mostrarDatos();
       
     
    }//GEN-LAST:event_jButtonCrearActionPerformed

    /**
     *  RETORNA TRUE  CUANDO LOS 3 ARGUMENTOS SON VERDADEROS 
     * @boolean inputHora
     * @boolean inputMinuto
     * @boolean inputSegundos
     * @return 
     */
    
    private boolean mensajeErrorInputs(boolean inputHora, boolean inputMinuto, boolean inputSegundos)
    {
        
        if(inputHora && inputMinuto && inputSegundos)
        {
            
            return true;
            
            
        } else{
           
            System.out.print("datos mal ingresados");
            
            if(!inputHora)
            {
                jHoraErrorMensaje.setText("Porfavor ingrese un valor valido");
            }
            
            if(!inputMinuto)
            {
                jMinutoErrorMensaje.setText("Porfavor ingrese un valor valido");
            }
            
            if(!inputSegundos)
            {
            jSegundosMensajeError.setText(" Porfavor ingrese un valor valido");
            
            }
            
            return false;
            
        }
       
      
    }
        
    
    private void clearInputTexts()
    {
        
       jTextHora.setText("");
       jTextMinuto.setText("");
       jTextSegundos.setText("");
        
    }
    
    
    private void clearErrorMensaje()
    {
        
         jSegundosMensajeError.setText("");
         
          jMinutoErrorMensaje.setText("");
           jHoraErrorMensaje.setText("");
        
        
    }
    
    
    private void jButtonGuardarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActualizarActionPerformed
        // TODO add your handling code here:
        
 
        int sizeRelojes = this.Relojes.GetRelojesSize();
        
                clearErrorMensaje();
                
            
       String minutoSinespacios = jTextMinuto.getText();
       String horaSinespacios = jTextHora.getText();
       String segundoSinespacios = jTextSegundos.getText();
       
       /*
       eliminamos los espacion de la entrada de datos
       */
       minutoSinespacios = minutoSinespacios.replaceAll("\\s+", "");
       horaSinespacios = horaSinespacios.replaceAll("\\s+", "");
       segundoSinespacios = segundoSinespacios.replaceAll("\\s+", "");
   
       
              ///VALIDATE HORA INPUT
       boolean validateinputHora;
       if(ControllerValidateInput.validateInputInteger(horaSinespacios )){
           
           int _hora = Integer.parseInt(horaSinespacios);
           if(ControllerValidateInput.validateHora(_hora)){
               
               validateinputHora = true;
               
           }else{  validateinputHora = false;}
       }else{validateinputHora = false;}
       
       
       ////// validacion de inputminutos
       boolean validateinputMinuto;
       
       if(ControllerValidateInput.validateInputInteger(minutoSinespacios )){
           
           int _minuto = Integer.parseInt(minutoSinespacios);
           if(ControllerValidateInput.validateMinuto(_minuto)){
               
               validateinputMinuto = true;
               
           }else{  validateinputMinuto = false;}
        }else{validateinputMinuto = false;}
       
       
       
       ///VALIDATE SEGUNDOSINPUT
       boolean validateinputSegundos;
         
        if(ControllerValidateInput.validateInputInteger(segundoSinespacios )){
           
           float _segundos = Integer.parseInt(segundoSinespacios);
           if(ControllerValidateInput.validateSegundos(_segundos)){
               
               validateinputSegundos = true;
               
           }else{  validateinputSegundos = false;}
        }else{validateinputSegundos = false;}
       
        /// Comprovamos las entradas de datos y mandamos un mensaje en caso de arojar un error
        boolean validate_inputs = mensajeErrorInputs(validateinputHora,validateinputMinuto,validateinputSegundos);
        
          
       if(validate_inputs){
       
           System.out.print("datos BIEN ingresados\n");
           
             int minuto = Integer.parseInt(minutoSinespacios);
              int hora = Integer.parseInt(horaSinespacios);
               int segundos = Integer.parseInt(segundoSinespacios);
               
                Reloj NuevoReloj = new Reloj(1,hora, minuto,segundos);
        
             /**
              * ACTUALZIAR DATOS DEL RELOJ
              */
                    if(sizeRelojes > 0)
                    {
                      for(int i = 0; i < this.Relojes.GetRelojesSize(); i++)
                        {
                           if(id_reloj == i)
                           {
                
                               
                 
                              Relojes.actualizarReloj(i, NuevoReloj);
                           }
            
                        }
                    }
             
             
                
                clearErrorMensaje();
                
                clearInputTexts();    
           
       }
       else{
           
            System.out.print("datos mal ingresados\n");
            
    
       }
      

       mostrarDatos();
        
        
        
    }//GEN-LAST:event_jButtonGuardarActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Reloj> RelojesLocal = new ArrayList<>();
        
        int sizeRelojes = this.Relojes.GetRelojesSize();
        
        if(sizeRelojes > 0){
           for(int i = 0; i < this.Relojes.GetRelojesSize(); i++)
           {
              if(id_reloj == i)
              {
                Relojes.eliminarReloj(i);
              }
            
           }
        }
        
        mostrarDatos();
        
        //Textmostrar(hora,minuto,"23");
        
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        
                ArrayList<Reloj> RelojesLocal = new ArrayList<>();
        
        int sizeRelojes = this.Relojes.GetRelojesSize();
        
        if(sizeRelojes > 0){
           for(int i = 0; i < this.Relojes.GetRelojesSize(); i++)
           {
              if(id_reloj == i)
              {
                String _hora = "" +this.Relojes.showRelojindex(i).getHora();
                String _minuto = "" + this.Relojes.showRelojindex(i).getMinuto();
                String _segundo = "" + this.Relojes.showRelojindex(i).getSegundo();
                  
                  Textmostrar(_hora,_minuto,_segundo);
                  
              }
            
           }
        }
        
        
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHoraActionPerformed

    private void jButtonCrearRelojBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearRelojBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCrearRelojBDActionPerformed

    private void jButtonRelojEliminarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelojEliminarBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelojEliminarBDActionPerformed

    private void jTextFieldminutoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldminutoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldminutoBDActionPerformed

    private void jTextFieldSegundoBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSegundoBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSegundoBDActionPerformed

    /**
     * VIZAULIZACION DE DATOS EN EL JTABLE
     */
    
    private void Textmostrar(String valor1, String valor2, String valor3)
    {
        
       jTextHora.setText(valor1);
       jTextMinuto.setText(valor2);
       jTextSegundos.setText(valor3);
        
        
    }
    
    
     private void mostrarDatos()
    {
        int Sizerelojes = this.Relojes.GetRelojesSize();
        
        String matriz[][] = new String[Sizerelojes][4];
        
        Reloj Relojobj = this.Relojes.showRelojindex(0);
        
          
        if(Sizerelojes > 0){
          for (int i = 0; i < Sizerelojes; i++) {
            
             
              matriz[i][0]= String.valueOf(i);
              matriz[i][1]="" + this.Relojes.showRelojindex(i).getHora();
              matriz[i][2]="" + this.Relojes.showRelojindex(i).getMinuto();
              matriz[i][3]="" + this.Relojes.showRelojindex(i).getSegundo();
        
            }
        
        
          jTable1.setModel(new javax.swing.table.DefaultTableModel(matriz, new String [] {"id_reloj","Hora","minuto","segundo"}));
        
        }  
        
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewRelojFra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewRelojFra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewRelojFra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewRelojFra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewRelojFra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonActualizarRelojDB;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrearRelojBD;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardarActualizar;
    private javax.swing.JButton jButtonRelojEliminarBD;
    private javax.swing.JLabel jHoraErrorMensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelShowReloj;
    private javax.swing.JLabel jMinutoErrorMensaje;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jSegundosMensajeError;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldHoraBD;
    private javax.swing.JTextField jTextFieldSegundoBD;
    private javax.swing.JTextField jTextFieldminutoBD;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextMinuto;
    private javax.swing.JTextField jTextSegundos;
    // End of variables declaration//GEN-END:variables
}
